name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true

# Security: Minimal permissions with OIDC
permissions:
  contents: write
  packages: write
  id-token: write # For OIDC
  attestations: write # For build attestations

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # v4.1.7
      with:
        fetch-depth: 0 # Required for GoReleaser

    - name: Set up Go
      uses: actions/setup-go@v5 # v5.0.2
      with:
        go-version: '1.24'
        check-latest: true

    - name: Cache Go modules
      uses: actions/cache@v4 # v4.1.2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-1.24-${{ hashFiles('**/go.sum') }}

    - name: Run tests before release
      run: make test

    - name: Run security scan before release
      run: |
        go vet ./...
        go install golang.org/x/vuln/cmd/govulncheck@latest
        govulncheck ./...

    - name: Install cosign for signing
      uses: sigstore/cosign-installer@v3 # v3.5.0

    - name: Install syft for SBOM generation
      uses: anchore/sbom-action/download-syft@v0 # v0.17.0

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6 # v6.0.0
      with:
        distribution: goreleaser
        version: '~> v2'
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}

    - name: Generate build attestation
      uses: actions/attest-build-provenance@v1 # v1.4.3
      with:
        subject-path: 'dist/markdocify_*'

  # Separate job for container builds (if needed)
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: release
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # v4.1.7

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3 # v3.6.1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3 # v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5 # v5.5.1
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6 # v6.6.1
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max